variables:
  imageName: my-node-app
  containerRegistry: myyacrregistry.azurecr.io
  acrConnection: 'acr-connection'        # Підключення до Azure Container Registry
  azureSubscription: 'azure-rm-connection'  # Підключення до Azure Resource Manager

steps:
- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    containerRegistry: '$(acrConnection)'
    repository: '$(containerRegistry)/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: AzureWebAppContainer@1
  displayName: Deploy to Azure Web App
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: 'my-webapp-docker'                   # Твоя назва Web App
    imageName: '$(containerRegistry)/$(imageName):latest'
