trigger:
  - main   # або master, залежно від назви гілки

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: my-node-app

steps:
- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    containerRegistry: 'acr-connection'  
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: AzureWebAppContainer@1
  displayName: Deploy to Azure Web App
  inputs:
    azureSubscription: 'acr-connection'
    appName: 'your-app-service-name'                   # назва твого Azure Web App
    imageName: '$(imageName):latest'
    containerRegistry: 'myyacrregistry.azurecr.io'
