trigger:
  - main  # або master, як у тебе в репозиторії

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: my-node-app
  containerRegistry: myyacrregistry.azurecr.io
  azureSubscription: 'acr-connection'  # ім'я твоєї service connection у Azure DevOps
  appName: my-webapp-docker

steps:
- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    containerRegistry: '$(azureSubscription)'
    repository: '$(containerRegistry)/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: AzureWebAppContainer@1
  displayName: Deploy to Azure Web App
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(appName)'
    imageName: '$(containerRegistry)/$(imageName):latest'
